UPDATE supply_chain_clean
SET
benefit_per_order = NULLIF(benefit_per_order, ''),
sales_per_customer = NULLIF(sales_per_customer, ''),
late_delivery_risk = NULLIF(late_delivery_risk, ''),
category_id = NULLIF(category_id, ''),
customer_id = NULLIF(customer_id, ''),
customer_zipcode = NULLIF(customer_zipcode, ''),
department_id = NULLIF(department_id, ''),
latitude = NULLIF(latitude, ''),
longitude = NULLIF(longitude, ''),
order_id = NULLIF(order_id, ''),
order_item_discount = NULLIF(order_item_discount, ''),
order_item_discount_rate = NULLIF(order_item_discount_rate, ''),
order_item_id = NULLIF(order_item_id, ''),
order_item_product_price = NULLIF(order_item_product_price, ''),
order_item_profit_ratio = NULLIF(order_item_profit_ratio, ''),
order_item_quantity = NULLIF(order_item_quantity, ''),
sales = NULLIF(sales, ''),
order_item_total = NULLIF(order_item_total, ''),
product_card_id = NULLIF(product_card_id, ''),
product_category_id = NULLIF(product_category_id, ''),
product_price = NULLIF(product_price, ''),
order_item_product_id = NULLIF(order_item_product_id, ''),
order_date=NULLIF(order_date, ''),
shipping_date=NULLIF(shipping_date, '');


CREATE TABLE supply_chain AS
SELECT
    type::text,
    days_for_shipping_real::INT,
    days_for_shipment_scheduled::INT,
    benefit_per_order::NUMERIC,
    sales_per_customer::NUMERIC,
    delivery_status,
    late_delivery_risk::INT,
    category_id::BIGINT,
    category_name,
    customer_city,
    customer_state,          -- Added
    customer_country,
    customer_id::BIGINT,
    customer_segment,
    department_id::BIGINT,
    department_name,
    latitude::NUMERIC,
    longitude::NUMERIC,
    market,
    order_city,
    order_country,
    order_date::TIMESTAMP,
    order_id::BIGINT,
    order_item_product_id::BIGINT,
    order_item_discount::NUMERIC,
    order_item_discount_rate::NUMERIC,
    order_item_id::BIGINT,
    order_item_product_price::NUMERIC,
    order_item_quantity::NUMERIC,
    sales::NUMERIC,
    order_item_total::NUMERIC,
    order_region,
    order_state,
    order_status,
    product_card_id::BIGINT,
    product_category_id::BIGINT,
    product_name,
    product_price::NUMERIC,
    product_status,
    shipping_date::TIMESTAMP,
    shipping_mode,
    original_order_item_id::BIGINT
FROM supply_chain_clean;